In [1]:
import numpy as np

# Datatypes and Attributes

In [2]:
#numpy main datatype is ndarray
a1=np.array([[1,2,3],[4,5,6]])
a1

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
a2=np.array([[1,2,3],
             [4,5,6],
            [7,8,9]])
a2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
a3=np.array([[[1,2,3],
             [4,5,6],
            [7,8,9]],
            [[1,2,3],
             [4,5,6],
            [7,8,9]]])
a3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [5]:
a2.shape

(3, 3)

In [6]:
 a1.ndim,a2.ndim,a3.ndim

(2, 2, 3)

In [7]:
a1.size,a2.size,a3.size

(6, 9, 18)

In [49]:
#Create a DataFrame from numpy array
import pandas as pd

In [9]:
df=pd.DataFrame(a2)
df

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

# Creating Arrays

In [10]:
o=np.ones(3)
o

array([1., 1., 1.])

In [11]:
z=np.zeros((2,3))
z


array([[0., 0., 0.],
       [0., 0., 0.]])

In [12]:
rangearray=np.arange(0,10,2)
rangearray

array([0, 2, 4, 6, 8])

In [13]:
randomarray=np.random.randint(0,10,size=(3,2))
randomarray

array([[2, 2],
       [9, 4],
       [8, 3]])

In [14]:
randomarray.size

6

In [15]:
randomarray.shape


(3, 2)

In [16]:
randomarrray2=np.random.random((2,3))
randomarrray2

array([[0.77487124, 0.64704591, 0.98131655],
       [0.83874103, 0.9370332 , 0.79726712]])

In [17]:
# pseudo random seed
np.random.seed(0)
r1=np.random.randint(0,10,size=(3,3))
r1

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2]])

# Viewing Arrays And Matrices

In [18]:
np.unique(r1)

array([0, 2, 3, 5, 7, 9])

In [19]:
r2=np.random.randint(0,10,size=(2,3,4,5))
r2

array([[[[4, 7, 6, 8, 8],
         [1, 6, 7, 7, 8],
         [1, 5, 9, 8, 9],
         [4, 3, 0, 3, 5]],

        [[0, 2, 3, 8, 1],
         [3, 3, 3, 7, 0],
         [1, 9, 9, 0, 4],
         [7, 3, 2, 7, 2]],

        [[0, 0, 4, 5, 5],
         [6, 8, 4, 1, 4],
         [9, 8, 1, 1, 7],
         [9, 9, 3, 6, 7]]],


       [[[2, 0, 3, 5, 9],
         [4, 4, 6, 4, 4],
         [3, 4, 4, 8, 4],
         [3, 7, 5, 5, 0]],

        [[1, 5, 9, 3, 0],
         [5, 0, 1, 2, 4],
         [2, 0, 3, 2, 0],
         [7, 5, 9, 0, 2]],

        [[7, 2, 9, 2, 3],
         [3, 2, 3, 4, 1],
         [2, 9, 1, 4, 6],
         [8, 2, 3, 0, 0]]]])

# Manipulating and comparing arrays

In [20]:
a1

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
o

array([1., 1., 1.])

In [22]:
a1+o

array([[2., 3., 4.],
       [5., 6., 7.]])

In [23]:
a1-o

array([[0., 1., 2.],
       [3., 4., 5.]])

# Aggregation

In [24]:
massive=np.random.random(10000)
massive[:30]

array([0.84138612, 0.26473016, 0.39782075, 0.55282148, 0.16494046,
       0.36980809, 0.14644176, 0.56961841, 0.70373728, 0.28847644,
       0.43328806, 0.75610669, 0.39609828, 0.89603839, 0.63892108,
       0.89155444, 0.68005557, 0.44919774, 0.97857093, 0.11620191,
       0.7670237 , 0.41182014, 0.67543908, 0.24979628, 0.31321833,
       0.96541622, 0.58846509, 0.65966841, 0.53320625, 0.23053302])

In [25]:
%timeit np.sum(massive)


8.6 µs ± 730 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [26]:
%timeit sum(massive)

826 µs ± 50.2 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [27]:
np.mean(massive)

0.5009790046094781

In [28]:
np.max(massive)

0.9999709462497284

In [29]:
np.min(massive)

2.0027530115096503e-05

In [30]:
np.std(massive)

0.28737869853455916

In [31]:
np.var(massive)

0.08258651637141705

In [32]:
# Standard Deviation is a squarroot of variance
np.sqrt(np.var(massive))

0.28737869853455916

# Reshaping and Transposing

In [33]:
a1.shape

(2, 3)

In [34]:
a3.shape

(2, 3, 3)

In [35]:
a1*a3

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

In [39]:
#reshape a1
a1=a1.reshape(2,3,1)

In [40]:
a1*a3

array([[[ 1,  2,  3],
        [ 8, 10, 12],
        [21, 24, 27]],

       [[ 4,  8, 12],
        [20, 25, 30],
        [42, 48, 54]]])

In [41]:
a2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [42]:
#Transpose
a2.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

# Dot product

In [44]:
np.dot(a2,a3)

array([[[ 30,  36,  42],
        [ 30,  36,  42]],

       [[ 66,  81,  96],
        [ 66,  81,  96]],

       [[102, 126, 150],
        [102, 126, 150]]])

In [45]:
a3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

# Dot Product example(nut butter sales)

In [47]:
# number of jars sold
np.random.seed(0)
salesamount=np.random.randint(20,size=(5,3))
salesamount

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [53]:
weeklysale=pd.DataFrame(salesamount,index=["Mon","Tue","Wed","Thur","Fri"],columns=["Almond Butter","Peanut Butter","Cashew Butter"])
weeklysale

Almond Butter  Peanut Butter  Cashew Butter
Mon              12             15              0
Tue               3              3              7
Wed               9             19             18
Thur              4              6             12
Fri               1              6              7

In [55]:
# Create prices array
prices=np.array([10,8,12])
prices

array([10,  8, 12])

In [58]:
butterprices=pd.DataFrame(prices.reshape(1,3),index=["Prices"],columns=["Almond Butter","Peanut Butter","Cashew Butter"])
butterprices

Almond Butter  Peanut Butter  Cashew Butter
Prices             10              8             12

In [62]:
# Shape are not aligned so transpose
Totalsales=prices.dot(salesamount.T)
Totalsales

array([240, 138, 458, 232, 142])

In [66]:
dailysales=butterprices.dot(weeklysale.T)
dailysales

Mon  Tue  Wed  Thur  Fri
Prices  240  138  458   232  142

In [67]:
weeklysale

Almond Butter  Peanut Butter  Cashew Butter
Mon              12             15              0
Tue               3              3              7
Wed               9             19             18
Thur              4              6             12
Fri               1              6              7

In [71]:
weeklysale["Total"]=dailysales.T
weeklysale

Almond Butter  Peanut Butter  Cashew Butter  Total
Mon              12             15              0    240
Tue               3              3              7    138
Wed               9             19             18    458
Thur              4              6             12    232
Fri               1              6              7    142

# Comparison Opeartor

In [75]:
a2


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [76]:
a3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [77]:
a2>a3

array([[[False, False, False],
        [False, False, False],
        [False, False, False]],

       [[False, False, False],
        [False, False, False],
        [False, False, False]]])

In [78]:
a2==a3

array([[[ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True]],

       [[ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True]]])

In [79]:
a2<a3

array([[[False, False, False],
        [False, False, False],
        [False, False, False]],

       [[False, False, False],
        [False, False, False],
        [False, False, False]]])

# Sorting

In [83]:
a2=np.random.randint(10,size=(3,3))
a2

array([[0, 3, 5],
       [0, 2, 3],
       [8, 1, 3]])

In [84]:
np.sort(a2)

array([[0, 3, 5],
       [0, 2, 3],
       [1, 3, 8]])

In [87]:
a1=np.array([1,2,3])
a1

array([1, 2, 3])

In [88]:
np.argsort(a1)

array([0, 1, 2], dtype=int64)

In [89]:
np.argmin(a1)

0

In [90]:
np.argmax(a1)

2

In [94]:
randomarray=np.random.randint(10,size=(5,3))
randomarray

array([[0, 4, 5],
       [5, 6, 8],
       [4, 1, 4],
       [9, 8, 1],
       [1, 7, 9]])

In [96]:
np.argmax(randomarray,axis=0)

array([3, 3, 4], dtype=int64)

In [97]:
np.argmax(randomarray,axis=1)

array([2, 2, 0, 0, 2], dtype=int64)

# Converting images into array

In [107]:
# Turn an image into array
from matplotlib.image import imread
car=imread("car.png")
car

array([[[0.5019608 , 0.50980395, 0.4862745 , 1.        ],
        [0.3372549 , 0.34509805, 0.30588236, 1.        ],
        [0.20392157, 0.21568628, 0.14901961, 1.        ],
        ...,
        [0.64705884, 0.7058824 , 0.54901963, 1.        ],
        [0.59607846, 0.63529414, 0.45882353, 1.        ],
        [0.44705883, 0.47058824, 0.3372549 , 1.        ]],

       [[0.44313726, 0.43529412, 0.40392157, 1.        ],
        [0.3137255 , 0.31764707, 0.27450982, 1.        ],
        [0.2       , 0.21176471, 0.14117648, 1.        ],
        ...,
        [0.5058824 , 0.5372549 , 0.4117647 , 1.        ],
        [0.49803922, 0.52156866, 0.39607844, 1.        ],
        [0.4       , 0.42745098, 0.34117648, 1.        ]],

       [[0.39607844, 0.38039216, 0.34117648, 1.        ],
        [0.31764707, 0.3137255 , 0.27450982, 1.        ],
        [0.28627452, 0.29411766, 0.24705882, 1.        ],
        ...,
        [0.44705883, 0.45882353, 0.32156864, 1.        ],
        [0.45882353, 0.482352

In [109]:
car.shape,car.size

((431, 575, 4), 991300)